### ISSUE TITLE
in_ncsf.dll crashes Winamp v5.666

### ISSUE THREAD

**Issue by Wryyyong** [CyberBotX/in_xsf#4]
Tested with:
\* `in_ncsf.dll` from https://www.cyberbotx.com/NCSF + zlib 1.2.8 DLL
\* `in_ncsf.dll` from #3 + zlib 1.2.8 DLL
\* `in_ncsf.dll` compiled by myself + zlib 1.2.11 DLL compiled by myself (as `libz.dll`)

All three result in the same thing: Winamp crashing upon starting the program.

Crash log and dump of my own compiled versions:
[_crash.zip](https://github.com/CyberBotX/in_xsf/files/5542186/_crash.zip)

---
**EDIT**:

Re-tested the plugin on Winamp versions 5.55 (identical to the latest SDK) and 5.8 (latest version). For some reason, it works without an issue on both versions.

I'd still like to look into this issue, though. What's so special about 5.666 that causes crashes with this plugin?

---
**EDIT 2**:

Apparently, it seems to be an issue with my Winamp configuration? Using a clean one generates no errors (so far). Still...

**Comment by CyberBotX** [comment]
That's all very strange that only .666 crashes, especially since I never encountered that myself back when I was still using .666 (I use .8 nowadays myself but in some places I still have .666.) I honestly have no idea why it only crashes for you in those instances you initially stated.
